"""update device model with new fields

Revision ID: 42e0a4a097f4
Revises: 
Create Date: 2025-01-30 14:36:19.313225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e0a4a097f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_initialized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.alter_column('device_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('device_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('assigned_to',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('last_active')
        batch_op.drop_column('connection_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_status', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DATETIME(), nullable=True))
        batch_op.alter_column('assigned_to',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('device_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('device_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('error_message')
        batch_op.drop_column('is_initialized')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
